version: "3.8"

name: launcher

services:
  launcher:
    build:
      context: ../../
      dockerfile: build/Dockerfile
    environment:
      - DOTENV_FILE=configs/dev/.env
      - DB_CONNECT_STRING=postgresql://hseuser:P@ssw0rd@db:5432/hsedb
      - WORKERS_ADDR=http://workers:8100
    ports:
      - "8087:8087"
      - "8088:8088"
    networks:
      - auth_hse-net

networks:
  auth_hse-net:
    external: true